apiVersion: batch/v1
kind: Job
metadata:
  name: andrewbailey-proportion-test-$TS
spec:
  ttlSecondsAfterFinished: 6000
  template:
    spec:
#      template:
#        metadata: # Apply a lable saying that we use NUMA node 0
#          labels:
#            usesnuma0: "Yes"
#      affinity: # Say that we should not schedule on the same node as any other pod with that label
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: usesnuma0
#                    operator: In
#                    values:
#                      - "Yes"
#              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: main
          imagePullPolicy: Always
          image: adbailey4/signalalign@sha256:a350ce89a00e23b96f2224a0ca8fc84e53ba7d44fde2c75331218c73b4833b1a
          env:
            - name: MODELS_BUCKET
              value: "bailey-k8s/functional_model_analysis/proportional_mc_calling_042021/dna_native-5mc_r9.4_native-5mc_run-1/models/0.9/"
            - name: OUTPUT_BUCKET
              value: "bailey-k8s/functional_model_analysis/proportional_mc_calling_042021/dna_native-5mc_r94_native-5mc_run-1/output/0.9/"
            - name: N_THREADS
              value: "12"
          command:
            - /bin/bash
            - -c
            - |
              set -e
              DEBIAN_FRONTEND=noninteractive apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y awscli
              #             download data
              aws s3 sync --no-progress s3://bailey-k8s/functional_model_analysis/proportional_mc_data/ .
              # aws s3 cp --no-progress s3://bailey-k8s/functional_model_analysis/proportional_mc_data/run_multiple_sa.sh .
              bash run_multiple_sa.sh "$(MODELS_BUCKET)" "$(N_THREADS)" "$(OUTPUT_BUCKET)"
              echo DONE
          volumeMounts:
            - mountPath: /root/.aws
              name: s3-credentials
            - mountPath: /data
              name: scratch-volume
          resources:
            limits:
              cpu: 12
              memory: "100Gi"
              ephemeral-storage: "100Gi"
      restartPolicy: Never
      volumes:
        - name: scratch-volume
          emptyDir: { }
        - name: s3-credentials
          secret:
            secretName: shared-s3-credentials
  backoffLimit: 0
